# Generated by Django 4.2 on 2026-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
