# Generated by Django 4.2 on 2026-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_carpeta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.seccion'),
        ),
    ]
