# Generated by Django 4.2 on 2026-04-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_archivo_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='files.carpeta'),
        ),
    ]
